homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 26
  unit_system: metric
  time_zone: Europe/London
  customize: !include customise/customise.yaml


http:
   api_password: !secret api_password
   ssl_certificate: !secret certificate
   ssl_key: !secret sslkey
   trusted_networks:
    - 192.168.0.0/24
    - 127.0.0.1
   ip_ban_enabled: True
   login_attempts_threshold: 3

updater:
  reporting: no

sun:
discovery:
ios:
conversation:
history:
recorder:
    purge_days: 5
    db_url: !secret mysql
logbook:
logger:
  default: info
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: critical
config:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret

mqtt:
  broker: 192.168.0.60
  port: 1883
  client_id: home-assistant-1
  username: !secret mqttuser
  password: !secret mqttpassword

 ########## Humax Switches ##########

####### Media Players #######
media_player:
  - platform: roku
  - platform: cast

###### Device Tracker #######
device_tracker:
  platform: nmap_tracker
  hosts: 192.168.0.1/24
  home_interval: 10
  track_new_devices: no
  consider_home: 300

device_tracker 2:
  - platform: bluetooth_tracker

device_tracker 3:
  - platform: ping
    interval_seconds: 60
    consider_home: 180
    hosts:
      router: 192.168.0.1

ifttt:
  key: !secret ifttt
  
upnp:
# port_mapping: false


####### Webcam ########
camera: !include camera/camera.yaml

android_ip_webcam:
  - host: 192.168.0.24
    port: 6779
    username: neil
    password: !secret cam_password
    name: Webcam
    switches:
      - overlay
      - night_vision
    sensors:
      - motion

emulated_hue:
  type: alexa
  host_ip: 192.168.0.60
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - switch

panel_iframe:
 mdiindex:
   title: MDI Icon Index
   icon: mdi:vector-square
   url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html



####Views####
group: !include group/group.yaml

########## RF Power Switches ##########
switch: !include switch/switch.yaml

########## Automations ##########
#automation: !include automation/automation.yaml
automation: !include_dir_list automation

########## Sensors ##########
sensor: !include sensor/sensor.yaml

####### Notifications ########
notify: !include notify/notify.yaml

####### Humax Commands ######
shell_command: !include shell/shell.yaml

####### LED Light ######
light: !include light/light.yaml

####### Input Select #######
input_select: !include inputs/select.yaml

######## Themes #########
frontend: !include themes/themes.yaml
