homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 26
  unit_system: metric
  time_zone: Europe/London
  customize: !include customise/customise.yaml
updater:
  reporting: no
sun:
discovery:
ios:
conversation:
history:
logbook:
config:
upnp:
camera: !include camera/camera.yaml
android_ip_webcam: !include camera/android webcam.yaml
mqtt: !include mqtt/mqtt.yaml
emulated_hue: !include hue/hue.yaml
group: !include group/group.yaml
switch: !include switch/switch.yaml
automation: !include_dir_list automation
sensor: !include sensor/sensor.yaml
notify: !include notify/notify.yaml
shell_command: !include shell/shell.yaml
light: !include light/light.yaml
input_select: !include inputs/select.yaml
frontend: !include themes/themes.yaml
device_tracker: !include device tracker/device tracker.yaml
nest: !include nest/nest.yaml
media_player: !include media player/media player.yaml
panel_iframe: !include iframe/iframe.yaml
logger: !include logger/logger.yaml
ifttt: !include ifttt/ifttt.yaml
http: !include http/http.yaml
recorder: !include recorder/recorder.yaml