default_view:
  entities:
  - group.family
  - group.living_room
  - group.conservatory
  - group.bedroom
  - group.nest
  - group.webcam
  - camera.webcam
  - updater.updater
  name: default_view
  view: true
automation:
  entities:
  - automation.family_home_lights
  - automation.lights_on_sunset
  - automation.fireplace_on_sunset
  - automation.lights_off_midnight
  - automation.tv_off_midnight
  - automation.hummy_on_630am
  - automation.bedroom_fan_on_2230
  - automation.broadband_drop
  - automation.auto_renew_ssl_cert
  name: Automation
  view: true
conservatory:
  entities:
  - sensor.conservatory_temperature
  - sensor.conservatory_humidity
  - sensor.conservatory_ldr
  - light.conservatory_led
  name: Conservatory
  view: false
tv_remote:
  entities:
  - group.humax_remote
  - switch.humax_power
  - switch.humax_mute
  - switch.humax_volume_up
  - switch.humax_volume_down
  - switch.humax_channel_up
  - switch.humax_channel_down
  - switch.humax_forward
  - switch.humax_back
  name: TV Remote
  view: false
humax_remote:
  entities:
  - input_select.channel
  name: Humax Remote 1
  view: true
