- platform: mqtt_json  
  name: "Conservatory LED"  
  state_topic: "bruh/sensornode1"  
  command_topic: "bruh/sensornode1/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0 
  
  
  
- platform: mqtt_json  
  name: "Front Door LED"  
  state_topic: "frontdoor"  
  command_topic: "frontdoor/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0 
  

- platform: mqtt_json  
  name: "Utility Room LED"  
  state_topic: "utility"  
  command_topic: "utility/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0 