- platform: mqtt_json  
  name: "Conservatory LED"  
  state_topic: "conservatory"  
  command_topic: "conservatory/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0 
  
  
  
- platform: mqtt_json  
  name: "Hallway LED"  
  state_topic: "hallway"  
  command_topic: "hallway/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0 
  

- platform: mqtt_json  
  name: "Utility Room LED"  
  state_topic: "utility"  
  command_topic: "utility/set"  
  brightness: true  
  flash: true  
  rgb: true  
  optimistic: false  
  qos: 0

  
- platform: mqtt_json
  name: "LED Strip"
  state_topic: "bruh/porch"
  command_topic: "bruh/porch/set"
  effect: true
  effect_list:
    - bpm
    - candy cane  
    - confetti  
    - cyclon rainbow  
    - dots  
    - fire  
    - glitter 
    - juggle  
    - lightning
    - noise  
    - police all  
    - police one  
    - rainbow  
    - rainbow with glitter  
    - ripple  
    - sinelon  
    - solid  
    - twinkle  
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0
  retain: true
  
- platform: mqtt
  name: LED Strip Green
  state_topic: "bruh/porch"
  command_topic: "bruh/porch/set"
  effect: true
  optimistic: false
  rgb_color: [0, 255, 0] # Green LED on
  
- platform: mqtt
  name: LED Strip Red
  state_topic: "bruh/porch"
  command_topic: "bruh/porch/set"
  effect: true
  optimistic: false
  rgb_color: [255, 0, 0] # Red LED on
  
- platform: mqtt
  name: LED Strip Blue
  state_topic: "bruh/porch"
  command_topic: "bruh/porch/set"
  effect: true
  optimistic: false
  rgb_color: [0, 0, 255] # Red LED on